services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_tuhistoria
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: api_tuhistoria
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tuhistoria
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  mongo_data:
